package com.divar.spring.utils.provider

import com.divar.spring.core.location.entity.City
import com.divar.spring.core.location.entity.NeighbourHood
import com.divar.spring.core.location.entity.Province

object LocationDataProvider {
    fun getData(): Triple<MutableList<Province>, MutableList<City>, MutableList<NeighbourHood>> {
        val provinces = mutableListOf(
            Province(name = "تهران"),
            Province(name = "البرز"),
            Province(name = "اصفهان"),
            Province(name = "خراسان رضوی"),
            Province(name = "فارس"),
            Province(name = "آذربایجان شرقی"),
            Province(name = "خوزستان"),
            Province(name = "گیلان"),
            Province(name = "مازندران"),
            Province( name = "سیستان و بلوچستان")
        )

        // Create cities
        val cities = mutableListOf(
            City(name = "تهران", province = provinces[0]),
            City(name = "اسلامشهر", province = provinces[0]),
            City(name = "ورامین", province = provinces[0]),
            City(name = "کرج", province = provinces[1]),
            City(name = "نظرآباد", province = provinces[1]),
            City(name = "ساوجبلاغ", province = provinces[1]),
            City(name = "اصفهان", province = provinces[2]),
            City(name = "کاشان", province = provinces[2]),
            City(name = "نجف‌آباد", province = provinces[2]),
            City(name = "مشهد", province = provinces[3]),
            City(name = "نیشابور", province = provinces[3]),
            City(name = "سبزوار", province = provinces[3]),
            City(name = "شیراز", province = provinces[4]),
            City(name = "مرودشت", province = provinces[4]),
            City(name = "کازرون", province = provinces[4]),
            City(name = "تبریز", province = provinces[5]),
            City(name = "مراغه", province = provinces[5]),
            City(name = "مرند", province = provinces[5]),
            City(name = "اهواز", province = provinces[6]),
            City(name = "آبادان", province = provinces[6]),
            City(name = "دزفول", province = provinces[6]),
            City(name = "رشت", province = provinces[7]),
            City(name = "انزلی", province = provinces[7]),
            City(name = "لاهیجان", province = provinces[7]),
            City(name = "ساری", province = provinces[8]),
            City(name = "بابل", province = provinces[8]),
            City(name = "آمل", province = provinces[8]),
            City(name = "زاهدان", province = provinces[9]),
            City(name = "چابهار", province = provinces[9]),
            City(name = "ایرانشهر", province = provinces[9])
        )

        // Create neighborhoods
        val neighborhoods = mutableListOf(
            NeighbourHood(name = "ولیعصر", city = cities[0]),
            NeighbourHood(name = "تجریش", city = cities[0]),
            NeighbourHood(name = "نیاوران", city = cities[0]),
            NeighbourHood(name = "شهرک گلستان", city = cities[1]),
            NeighbourHood(name = "شهرک آزادی", city = cities[1]),
            NeighbourHood(name = "میدان نماز", city = cities[1]),
            NeighbourHood(name = "قاسم‌آباد", city = cities[2]),
            NeighbourHood(name = "پاکدشت", city = cities[2]),
            NeighbourHood(name = "جوادیه", city = cities[2]),
            NeighbourHood(name = "گلشهر", city = cities[3]),
            NeighbourHood(name = "عظیمیه", city = cities[3]),
            NeighbourHood(name = "گوهردشت", city = cities[3]),
            NeighbourHood(name = "نظرآباد قدیم", city = cities[4]),
            NeighbourHood(name = "شهرک صنعتی", city = cities[4]),
            NeighbourHood(name = "ولیعصر", city = cities[4]),
            NeighbourHood(name = "شهرک ساوجبلاغ", city = cities[5]),
            NeighbourHood(name = "اشتهارد", city = cities[5]),
            NeighbourHood(name = "هشتگرد", city = cities[5]),
            NeighbourHood(name = "جلفا", city = cities[6]),
            NeighbourHood(name = "ملک‌شهر", city = cities[6]),
            NeighbourHood(name = "سپاهان‌شهر", city = cities[6]),
            NeighbourHood(name = "فین", city = cities[7]),
            NeighbourHood(name = "قمصر", city = cities[7]),
            NeighbourHood(name = "نیاسر", city = cities[7]),
            NeighbourHood(name = "ویلاشهر", city = cities[8]),
            NeighbourHood(name = "کهریزسنگ", city = cities[8]),
            NeighbourHood(name = "گلپایگان", city = cities[8]),
            NeighbourHood(name = "کوهسنگی", city = cities[9]),
            NeighbourHood(name = "احمدآباد", city = cities[9]),
            NeighbourHood(name = "طرقبه", city = cities[9]),
            NeighbourHood(name = "کوهسنگی", city = cities[10]),
            NeighbourHood(name = "عطار", city = cities[10]),
            NeighbourHood(name = "شهرک فرهنگیان", city = cities[10]),
            NeighbourHood(name = "طوس", city = cities[11]),
            NeighbourHood(name = "خیام", city = cities[11]),
            NeighbourHood(name = "اسدی", city = cities[11]),
            NeighbourHood(name = "قصرالدشت", city = cities[12]),
            NeighbourHood(name = "ستارخان", city = cities[12]),
            NeighbourHood(name = "عفیف‌آباد", city = cities[12]),
            NeighbourHood(name = "مرودشت قدیم", city = cities[13]),
            NeighbourHood(name = "شهرک صدرا", city = cities[13]),
            NeighbourHood(name = "ولیعصر", city = cities[13]),
            NeighbourHood(name = "قائمیه", city = cities[14]),
            NeighbourHood(name = "کازرون جدید", city = cities[14]),
            NeighbourHood(name = "بخش مرکزی", city = cities[14]),
            NeighbourHood(name = "ولیعصر", city = cities[15]),
            NeighbourHood(name = "شهناز", city = cities[15]),
            NeighbourHood(name = "چایکنار", city = cities[15]),
            NeighbourHood(name = "قپان", city = cities[16]),
            NeighbourHood(name = "قدیمی", city = cities[16]),
            NeighbourHood(name = "شهرک صنعتی", city = cities[16]),
            NeighbourHood(name = "شهرک مرند", city = cities[17]),
            NeighbourHood(name = "مرند قدیم", city = cities[17]),
            NeighbourHood(name = "مرند جدید", city = cities[17]),
            NeighbourHood(name = "کوی انقلاب", city = cities[18]),
            NeighbourHood(name = "کوی ملت", city = cities[18]),
            NeighbourHood(name = "گلستان", city = cities[18]),
            NeighbourHood(name = "بریم", city = cities[19]),
            NeighbourHood(name = "ذوالفقاری", city = cities[19]),
            NeighbourHood(name = "ولیعصر", city = cities[19]),
            NeighbourHood(name = "شهرک دزفول", city = cities[20]),
            NeighbourHood(name = "شهرک قدیم", city = cities[20]),
            NeighbourHood(name = "شهرک جدید", city = cities[20]),
            NeighbourHood(name = "معلم", city = cities[21]),
            NeighbourHood(name = "پیربازار", city = cities[21]),
            NeighbourHood(name = "گلسار", city = cities[21]),
            NeighbourHood(name = "آبکنار", city = cities[22]),
            NeighbourHood(name = "کوهی", city = cities[22]),
            NeighbourHood(name = "شهرک صنعتی", city = cities[22]),
            NeighbourHood(name = "سیمبر", city = cities[23]),
            NeighbourHood(name = "سیمبر قدیم", city = cities[23]),
            NeighbourHood(name = "سیمبر جدید", city = cities[23]),
            NeighbourHood(name = "بلوار کشاورز", city = cities[24]),
            NeighbourHood(name = "هولا", city = cities[24]),
            NeighbourHood(name = "معلم", city = cities[24]),
            NeighbourHood(name = "زرگرمحله", city = cities[25]),
            NeighbourHood(name = "بهنمیر", city = cities[25]),
            NeighbourHood(name = "شهرک صنعتی", city = cities[25]),
            NeighbourHood(name = "پل سفید", city = cities[26]),
            NeighbourHood(name = "شیرگاه", city = cities[26]),
            NeighbourHood(name = "زاغمرز", city = cities[26]),
            NeighbourHood(name = "بلوار امیرکبیر", city = cities[27]),
            NeighbourHood(name = "شهرک امام", city = cities[27]),
            NeighbourHood(name = "حافظ", city = cities[27]),
            NeighbourHood(name = "شهرک صنعت", city = cities[28]),
            NeighbourHood(name = "بندر کنارک", city = cities[28]),
            NeighbourHood(name = "خیابان ساحلی", city = cities[28]),
            NeighbourHood(name = "محمدان", city = cities[29]),
            NeighbourHood(name = "بزمان", city = cities[29]),
            NeighbourHood(name = "شهرک صنعتی", city = cities[29])
        )
        return Triple(provinces, cities, neighborhoods)
    }
}